<#
.SYNOPSIS
    Installs the pre-commit hook that blocks commits with a stale signature.
.DESCRIPTION
    One-time setup for the maintainer's working copy. After cloning the repo
    on a new machine, run:

        powershell -ExecutionPolicy Bypass -File tools\install-hooks.ps1

    The hook fires only on commits that touch patch.ps1, patch.ps1.sig, or
    install.ps1, and refuses the commit if tools\verify-signature.ps1 fails.

    This is a belt-and-suspenders safeguard: even if it's skipped (fresh clone
    that hasn't been hooked yet), install.ps1 still aborts on end-user machines
    when the downloaded signature doesn't match. The hook just catches the
    mistake earlier, before push.
#>
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$hooksDir = Join-Path $repoRoot '.git\hooks'

if (-not (Test-Path $hooksDir)) {
    Write-Host "No .git\hooks directory at $hooksDir." -ForegroundColor Red
    Write-Host "Are you running from a real git clone?" -ForegroundColor Yellow
    exit 1
}

$hookPath = Join-Path $hooksDir 'pre-commit'

# LF line endings -- git on Windows runs hooks via Git-bash which expects POSIX.
$hookBody = @"
#!/usr/bin/env bash
# Auto-generated by tools/install-hooks.ps1 -- verifies patch.ps1.sig matches
# patch.ps1 before allowing a commit that touches either file.
if git diff --cached --name-only | grep -qE '^(patch\.ps1|patch\.ps1\.sig|install\.ps1)$'; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File tools/verify-signature.ps1
    rc=`$?
    if [ `$rc -ne 0 ]; then
        echo ""
        echo "ERROR: signature verification failed. Commit BLOCKED."
        echo "If you intentionally changed patch.ps1, run:"
        echo "  .\\tools\\sign-release.ps1"
        echo "then 'git add patch.ps1.sig' and retry the commit."
        exit 1
    fi
fi
exit 0
"@

# Strip CRs that may have crept in from here-string handling.
$hookBody = $hookBody -replace "`r`n", "`n"

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText($hookPath, $hookBody, $utf8NoBom)

Write-Host "Pre-commit hook installed at $hookPath" -ForegroundColor Green
Write-Host "It will block commits touching patch.ps1 / patch.ps1.sig / install.ps1" -ForegroundColor Cyan
Write-Host "if patch.ps1.sig does not match the staged patch.ps1." -ForegroundColor Cyan
